- name: Setting Up Bash
  package:
    name:
      - bash-completion
    extra_args: --noconfirm --needed

- name: aliases
  template:
    dest: $HOME/.aliases
    src: aliases.j2
- name: bash_profile
  template:
    dest: $HOME/.bash_profile
    src: bash_profile.j2
- name: bashrc
  template:
    dest: $HOME/.bashrc
    src: bashrc.j2