- name: Setting Up Bash
  package:
    name:
      - bash-completion
    extra_args: --noconfirm --needed

- name: aliases
  template:
    dest: "{{ home_directory }}/.aliases"
    src: aliases.j2
- name: bashrc
  template:
    dest: "{{ home_directory }}/.bashrc"
    src: bashrc.j2