- name: Setting Up Bash
  package:
    name:
      - bash-completion
    extra_args: --noconfirm --needed
    
- name: bashrc
  template:
    dest: "{{ home_directory }}/.bashrc"
    src: bashrc.j2
    owner: mrgrim
    group: mrgrim