---
- hosts: all
  connection: local
  become: true
  roles:
    - bin
    - bash
    - sddm
    - pacman
    - ansible_user
    - systemd
    - cron
    - i3
    - dunst
    - alacritty
    - feh
  tasks:
    - name: Install Common
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - base-devel
        - curl
    - name: Install Software
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - gst-libav
        - ttf-firacode-nerd
        - phonon-qt5-gstreamer
        - gst-plugins-good
        - qt5-quickcontrols
        - qt5-graphicaleffects
        - qt5-multimedia
        - cronie
        - syncthing
        - firefox
        - alacritty
        - thunderbird
        - btop
        - bitwarden
        - signal-desktop
        - telegram-desktop
        - rofi
        - autotiling
        - steam
        - amberol
        - mpv