---
- hosts: all
  connection: local
  become: true
  vars:
    HOME: /home/mrgrim
  roles:
    - pacman
    - ansible_user
    - systemd
    - cron
    - i3
    - dunst
    - polybar
  tasks:
    - name: Install Software
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - sddm
        - gst-libav
        - honon-qt5-gstreamer
        - gst-plugins-good
        - qt5-quickcontrols
        - qt5-graphicaleffects
        - qt5-multimedia
        - zsh
        - cronie
        - syncthing
        - firefox
        - alacritty
        - thunderbird
        - btop
        - bitwarden
        - signal-desktop
        - telegram-desktop
        - rofi
        - feh
        - autotiling
        - steam
        - amberol
        - mpv