---
- hosts: all
  connection: local
  become: true
# COMMON
  tasks:
    - name: Create Ansible user
      import_tasks: tasks/ansible_setup/user.yml
    - name: backup pacman
      import_tasks: tasks/backup_pacman.yml
    - name: Copy dotfiles to user's home directory
      import_tasks: tasks/copy_dotfiles.yml
    - name: Install packages
      import_tasks: tasks/install_packages.yml
  roles:
    - cron
    - i3
    - dunst
    - polybar