---
- hosts: all
  connection: local
  become: true

- name: Desktop Configuration
  import_playbook: playbooks/desktop.yml
  when: ansible_hostname == 'desktop'

- name: Laptop Configuration
  import_playbook: playbooks/laptop.yml
  when: ansible_hostname == 'laptop'

- name: Phone Configuration
  import_playbook: playbooks/phone.yml
  when: ansible_hostname == 'phone'