---
- hosts: all
  connection: local
  become: true
# COMMON
  tasks:
    - name: Install packages
      import_tasks: tasks/install_packages.yml

# ANSIBLE SETUP
    - name: Create Ansible user
      import_tasks: tasks/ansible_setup/user.yml

    - name: Add ansible-pull cron job
      import_tasks: tasks/ansible_setup/cron.yml

# MAIN LOGIC
    - name: backup pacman
      import_tasks: tasks/backup_pacman.yml
    - name: Copy dotfiles to user's home directory
      import_tasks: tasks/copy_dotfiles.yml
