---
- hosts: all
  connection: local

- name: Desktop Configuration
  import_playbook: playbooks/desktop.yml
  when: ansible_hostname == 'desktop'
  become: true

- name: Laptop Configuration
  import_playbook: playbooks/laptop.yml
  when: ansible_hostname == 'laptop'
  become: true

- name: Phone Configuration
  import_playbook: playbooks/phone.yml
  when: ansible_facts.os_family == 'OtherLinux'