---
- hosts: all
  connection: local
  become: true

  tasks:
##############################################
  - name: install packages
    package:
      name:
        - crontab
        - btop
        - firefox
##############################################
  - name: Creating Ansible User
    user:
      name: ansible
      system: yes
  - name: Set Ansible as sudo
    copy:
      src: files/sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440
  - name: Add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible
      minute: "*/10"
      job: ansible-pull -o -U git@github.com:0x7C2f/configuration.git