---
- hosts: all
  connection: local
  become: true
  vars:
    HOME: /home/mrgrim
  roles:
    - ansible_user
    - systemd
    - cron
    - i3
    - dunst
    - polybar
  tasks:
    - name: Full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true
    - name: Install Software
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - sddm
        - zsh
        - cronie
        - syncthing
        - firefox
        - alacritty
        - thunderbird
        - btop
        - bitwarden
        - signal-desktop
        - telegram-desktop
        - rofi
        - feh
        - autotiling
        - steam
        - amberol