---
#
# DOTFILES
# 
  - name: copy .zshrc
    copy:
      src: files/zshrc
      dest: /home/mrgrim/.zshrc
      owner: mrgrim
      group: mrgrim
  - name: copy .xinitrc
    copy:
      src: files/xinitrc
      dest: /home/mrgrim/.xinitrc
      owner: mrgrim
      group: mrgrim
#
# FOLDERS
#
  - name: Polybar Configuration
    copy:
      src: files/polybar/
      dest: /home/mrgrim/.config/polybar/
      owner: mrgrim
      group: mrgrim