---
- name: Copy systemd service unit file
  copy:
    src: rtkit-daemon.service
    dest: /etc/systemd/system/{{ systemd_service_name }}.service

- name: Ensure service is {{ systemd_service_state }}
  systemd:
    name: "{{ systemd_service_name }}"
    state: "{{ systemd_service_state }}"
    enabled: "{{ systemd_service_enabled }}"
  notify:
    - restart your service
