- name: Installing feh
  package:
    name:
      - feh
    extra_args: --noconfirm --needed

- name: Deploy Wallpaper
  copy:
    src: background.jpg
    dest: "{{home_directory}}/.config"
    owner: mrgrim
    group: mrgrim