---
- name: Install Chezmoi
  become: yes
  become_user: root
  shell: >
    curl -fsLS https://git.io/chezmoi | sh -s -- -b {{ chezmoi_install_dir }}
  args:
    creates: "{{ chezmoi_install_dir }}/chezmoi"

- name: Initialize Chezmoi with dotfiles repository
  become: no
  command: >
    sh -c "$(curl -fsLS https://git.io/chezmoi)" -- init --apply {{ chezmoi_github_username }}
  environment:
    GITHUB_USERNAME: "{{ chezmoi_github_username }}"
