---
- name: Install i3
  pacman:
    name: i3-wm
    state: present
  become: yes

- name: Deploy i3 configuration
  template:
    dest: "{{home_directory}}/.config/i3/config"
    src: config.j2
    owner: mrgrim
    group: mrgrim

- name: Ensure scripts directory exists
  ansible.builtin.file:
    path: "{{home_directory}}/.config/i3/scripts/"
    state: directory

- name: Deploying Keyboard Settings
  template:
    dest: "{{home_directory}}/.config/i3/scripts/keyboard-settings.sh"
    src: config.j2
    mode: '755'
    owner: mrgrim
    group: mrgrim