---
- name: Install i3
  pacman:
    name: i3-wm
    state: present
  become: yes

- name: Deploy i3 configuration
  template:
    dest: "{{home_directory}}/.config/i3/config"
    src: config.j2
    owner: mrgrim
    group: mrgrim