---
- name: Ensure pacman.conf is configured
  template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
  notify: Restart pacman
- name: Ensure /etc/pacman.d/hooks directory exists
  file:
    path: /etc/pacman.d/hooks
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: Create paccache hook file
  template:
    src: paccache.hook.j2
    dest: /etc/pacman.d/hooks/paccache.hook
    owner: root
    group: root
    mode: '0644'
- name: Install Paccache
  community.general.pacman:
    name: "pacman-contrib"
    state: present
- name: Full system upgrade
  community.general.pacman:
    update_cache: true
    upgrade: true