---
- name: Install polybar
  pacman:
    name: "{{ polybar_package_name }}"
    state: present
  become: yes

- name: Create polybar config directory
  file:
    path: "{{ polybar_config_path | dirname }}"
    state: directory
    mode: '0755'

- name: Deploy polybar configuration
  copy:
    src: config.ini
    dest: "{{ polybar_config_path }}"
    owner: mrgrim
    group: mrgrim

- name: Deploy polybar launch script
  copy:
    src: launch.sh
    dest: "{{ polybar_config_path }}"
    owner: mrgrim
    group: mrgrim