---
- name: Install polybar
  pacman:
    name: "polybar]"
    state: present
  become: yes

- name: Create polybar config directory
  file:
    path: "{{ home_directory }}/.config/polybar"
    state: directory
    mode: '0755'

- name: Deploy polybar configuration
  copy:
    src: config.ini
    dest: "{{ home_directory }}/.config/polybar"
    owner: mrgrim
    group: mrgrim

- name: Deploy polybar launch script
  copy:
    src: launch.sh
    dest: "{{ home_directory }}/.config/polybar"
    owner: mrgrim
    group: mrgrim