---
- name: Install polybar
  pacman:
    name: "polybar"
    state: present
  become: yes

- name: Create polybar config directory
  file:
    path: "{{ home_directory }}/.config/polybar"
    state: directory
    owner: mrgrim
    group: mrgrim
    mode: '0755'

- name: Deploy polybar configuration
  template:
    dest: "{{ home_directory }}/.config/polybar/config.ini"
    src: config.j2
    owner: mrgrim
    group: mrgrim

- name: Deploy polybar configuration
  template:
    dest: "{{ home_directory }}/.config/polybar/launch.sh"
    src: launch.j2
    owner: mrgrim
    group: mrgrim
    mode: a+x