export ZSH="$HOME/.oh-my-zsh"
export PATH="$PATH:/home/mrgrim/.spicetify:/home/mrgrim/.local/bin"

ZSH_THEME="robbyrussell"

plugins=(git)

source $ZSH/oh-my-zsh.sh

DISABLE_AUTO_UPDATE="true"


alias getwindowinfo='xprop | grep -E "WM_CLASS|WM_NAME"'
alias getclassinfo='xwininfo -tree -root | grep -E "class"'


