export ZSH="$HOME/.oh-my-zsh"
export PATH="$PATH:/home/mrgrim/.spicetify:/home/mrgrim/.local/bin"

ZSH_THEME="robbyrussell"

plugins=(git)

source $ZSH/oh-my-zsh.sh

DISABLE_AUTO_UPDATE="true"


alias getwindowinfo='xprop | grep -E "WM_CLASS|WM_NAME"'
alias getclassinfo='xwininfo -tree -root | grep -E "class"'


python_venv() {
  MYVENV=./venv
  # when you cd into a folder that contains $MYVENV
  [[ -d $MYVENV ]] && source $MYVENV/bin/activate > /dev/null 2>&1
  # when you cd into a folder that doesn't
  [[ ! -d $MYVENV ]] && deactivate > /dev/null 2>&1
}
autoload -U add-zsh-hook
add-zsh-hook chpwd python_venv

python_venv
