---
- hosts: all
  connection: local
  become: true
  vars:
    ansible_user: mrgrim
    home_directory: /home/mrgrim

  roles:
    - bin
    - bash
    - sddm
    - pacman
    - ansible_user
    - systemd
    - cron
    - i3
    - dunst
    - alacritty
    - feh
    - firefox
    - thunar
    - ruby
    - python
    - polybar
    - vscode
  tasks:
    - name: Install Common packages
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - base-devel
        - curl

    - name: Install Software packages
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - gst-libav
        - ttf-firacode-nerd
        - phonon-qt5-gstreamer
        - gst-plugins-good
        - qt5-quickcontrols
        - qt5-graphicaleffects
        - qt5-multimedia
        - syncthing
        - thunderbird
        - btop
        - bitwarden
        - signal-desktop
        - telegram-desktop
        - rofi
        - autotiling
        - steam
        - amberol
        - mpv
        - weechat
        - fortune-mod
        - ruby
        - ffmpeg
        - libx264
        - gst-libav 
        - gst-plugins-good
        - gst-plugins-bad 
        - gst-plugins-ugly
        - vlc

